version: '3.9'

services:
    api:
        build: .
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 4040:4000
        depends_on:
            - postgres
        # environment:
        #     - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres?schema=public
        restart: always

    postgres:
        image: postgres
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: always

    client: 
        build: ../front
        ports: 
          - 3000:3000
        depends_on: 
          - api 
        volumes: 
          - ../front:/app
          - /app/node_modules
        restart: always
