version: '3.9'

services:
    api:
        build: .
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 4040:4000
        depends_on:
            - postgres-test
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres-test?schema=public&connect_timeout=300
        restart: always
        command: sh -c "yarn run db:migrate && tail -f /dev/null"

    postgres-test:
        image: postgres
        container_name: postgres-test
        hostname: postgres
        # ports:
        #     - 5433:5433
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: always

    client:
        build: ../2203-wns-pairet-compito-front
        ports:
            - 3000:3000
        depends_on:
            - api
        volumes:
            - ../2203-wns-pairet-compito-front:/app
            - /app/node_modules
        restart: always
